### ISSUE TITLE
Two sidebars are not working

### ISSUE THREAD

**Issue by yustiks** [Turbo87/leaflet-sidebar#85] opened 2022-02-08 08:51 UTC
I can not run examples

**Comment by zedd45** [comment] 2022-05-05 20:43
Duplicate of #79 

please keep in mind That stack traces and additional information are helpful in solving problems like this.

I don’t recall if we have a contribution guideline but I will see if I can put one of those together. In the meantime check out the other issue for some information

**Closed by zedd45** 2022-05-05 20:43 UTC
