### ISSUE TITLE
Conflict with angular ui-bootstrap dropdown button?

### ISSUE THREAD

**Issue by haoliangyu** [Turbo87/leaflet-sidebar#37] opened 2016-01-07 02:41 UTC
I try to make the sidebar and an angular ui-bootstrap dropdown button work together. But the problem is if I initialize the sidebar, the dropdown button will break into a button and a list. If I comment the sidebar initialization code, the dropdwon button will be grouped as usual. Is there a conflict?

My code is shown below and here is a [plunker example](http://plnkr.co/edit/rsszUAxayjXfygaHkpUa).

index.html

```
<!DOCTYPE html>
<html ng-app="ui.bootstrap.demo">
	<head>
        <title>Map Sidebar Dropdown Hell</title>

        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-animate.js"></script>
        <script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.14.3.js"></script>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
		
		<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css">
		<link rel="stylesheet" href="http://cdn.rawgit.com/Turbo87/leaflet-sidebar/master/src/L.Control.Sidebar.css">
		<link rel="stylesheet" href="style.css">
		
		<script src="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
		<script src="http://cdn.rawgit.com/Turbo87/leaflet-sidebar/master/src/L.Control.Sidebar.js"></script>
		<script src="script.js"></script>
	</head>
	
	<body >
    <div id="content" ng-controller="DropdownCtrl">
      <div id="map"></div>
      <div id="sidebar">
        this is a sidebar.
      </div>
      
    <!-- Single button -->
    <div class="btn-group" uib-dropdown is-open="status.isopen">
      <button id="single-button" type="button" class="btn btn-primary" uib-dropdown-toggle ng-disabled="disabled">
        Button dropdown <span class="caret"></span>
      </button>
      <ul class="uib-dropdown-menu" role="menu" aria-labelledby="single-button">
        <li role="menuitem"><a href="#">Action</a></li>
        <li role="menuitem"><a href="#">Another action</a></li>
        <li role="menuitem"><a href="#">Something else here</a></li>
        <li class="divider"></li>
        <li role="menuitem"><a href="#">Separated link</a></li>
      </ul>
    </div>
      
    </div>
	</body>
	
</html>
```

script.js

```
angular.module('ui.bootstrap.demo', ['ngAnimate', 'ui.bootstrap']);
angular.module('ui.bootstrap.demo').controller('DropdownCtrl', function ($scope) {
	  var map = new L.Map('map', {
            zoom: 10,
            minZoom: 8,
            maxZoom: 12
        }); 
    var osmUrl='http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
		var osm = new L.TileLayer(osmUrl, {minZoom: 8, maxZoom: 12});
    		map.setView(new L.LatLng(-36.5, 143.98), 6);
    		map.addLayer(osm);
    		
    // Comment following lines to group the button and dropdown list
    var sidebar = L.control.sidebar('sidebar', {
		    position: 'left'
		});

    map.addControl(sidebar);
    sidebar.show();

});
```

**Comment by zedd45** [comment] 2016-01-08 19:58
Possible duplicate of #31 ?

**Comment by Turbo87** [comment] 2016-01-13 10:24
Possibly, but then it should work with the current release. I can't support every single framework though. Feel free to find the problem and fix it but I won't put any time into this myself.

**Closed by Turbo87** 2016-01-13 10:24 UTC
